### ISSUE TITLE
Swap Roles and Life Cycle

### ISSUE THREAD

**Issue by dpv021** [hdunne/redballoon#18]
As the different bee roles are referenced in the life cycle, put it before (to the left of) the life cyle

**Comment by dpv021** [comment]
*cycle

**Comment by hdunne** [comment]
Thoughts on this? When reading through the caption of Life Cycle it talks about when the worker bee builds and when the queen lays eggs and "Remember that drones come from unfertilized eggs" but this information is not brought up until the next subsection/category - Roles. Based on this, it would make sense to have Roles before Life Cycle....

**Comment by hdunne** [comment]
done by team 12-9
