### ISSUE TITLE
scorm cloud drag and drop

### ISSUE THREAD

**Issue by hdunne** [hdunne/redballoon#40]
I know that the drag and drop needs to be dropped where there is not text, but when you grab the dragger the cursor automatically grabs in a specific spot. There is no way to drop in the dragger bay without landing on the text. (This is specifically on the first dragger in the why bees? knowledge assessment)

**Comment by dpv021** [comment]
works as indicated in firefox (linux), no issues

**Comment by dpv021** [comment]
from SCORM: firefox, chrome and safari no issues
