### ISSUE TITLE
Certificate page is not displayed after final quiz is successfully passed.

### ISSUE THREAD

**Issue by hdunne** [hdunne/redballoon#53]

**Comment by hdunne** [comment]
SCORM computer also did not show certificate or a score on SCORM.

**Comment by hdunne** [comment]
certificate was not available during review in class. diane will look at how to get certificate option to print if/only if quiz is passed....no less than 1 question failed = 83/100, 2 questions failed is 68/100=F.

**Comment by dpv021** [comment]
fixed
