### ISSUE TITLE
PDF files are missing from links

### ISSUE THREAD

**Issue by hdunne** [hdunne/redballoon#57]

**Comment by dpv021** [comment]
![screen shot 2015-11-12 at 7 17 04 pm](https://cloud.githubusercontent.com/assets/13991099/11136194/03aefa5c-8972-11e5-81cd-25274e0b8523.png)

**Comment by hdunne** [comment]
not showing up in scorm

**Comment by dpv021** [comment]
fixed. Link will either open or download PDF.
